# Generated by Django 4.2.7 on 2023-11-08 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveBigIntegerField()),
                ('unidad', models.CharField(choices=[('un', 'Unidad'), ('paquete', 'Paquete'), ('kg', 'Kilos'), ('lb', 'Libras'), ('lt', 'Litros')], max_length=200)),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('categoria', models.CharField(choices=[('alimentos', 'Alimentos'), ('limpieza', 'Limpieza'), ('ropa', 'Ropa'), ('electrónicos', 'Electrónicos'), ('hogar', 'Hogar'), ('belleza', 'Belleza'), ('juguetes', 'Juguetes'), ('otros', 'Otros')], max_length=200)),
                ('comprado', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'order_with_respect_to': 'user',
            },
        ),
    ]
